language: java

notifications:
  slack:
    secure: FIHlTn/YO7Wgumm1uIqmoEsqjQA7fV0AE94Rjc5yKzM3AquQa8HicgDVVk0d2GrKRnl0xt3j4ZJV//VJyIjlCd/QVKuj48R2ChjEY2im3+99HFPafCUI5/S2uyowKU6mJTFonH9v6p41eqxdbiAxJdDGOT0V2Gpt3UBSNuHz8ED9/aIHqv+P7M+VD6Xd2XYwctPniWlaSWx57sWcnG/VkFG45qFQAyha64uxOOe4M3ZmG/n5FfauZ8cBVLiRKEIr+CyNhh1ujfzi7+4uzMlSNL5t/BbZamAQuZzqGzGQ9RVvIlyPgUGNJtDEE/hWS09aagXF5T6EMj00szizErh4J1/x4qZwml5+TcBN31E0QmAhCtZe85sr3tYgic+hEz9XX1yymQzf/C7n4to2yNvq0r4g51xDk8IuP95WEh7zaqLlvFZvBFgxpHZBMYlRvhytjOYDeIFRMcGwHZcXosaG2ejqDwcGq/LC4oeG4sSwmg9sdRrtcmcanrNqrBka86WYO6LntI3JdZ86/1ACEUHzhCCwvrKELc9Ji1xxGAgS7QKH+s2/hnJuiMyv73gOVLKYC+wPMLt+fvOmPLSEl+PJiAIlToBq1KUBg03RSQLfPOLD7OrJ8VvDZsEPwejqlGDyc4wRglS9OTi7SnN5LYHSDNDdGdREegWqq9qDHEYEVLI=

env:
  matrix:
    - ENGINE=lucee@4.5
    - ENGINE=lucee@5
    - ENGINE=adobe@11
    - ENGINE=adobe@2016

branches:
  only:
  - development
  - master

dist: trusty

sudo: required

before_install:
  # CommandBox Keys
  - sudo apt-key adv --keyserver keys.gnupg.net --recv 6DA70622
  - sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a
    /etc/apt/sources.list.d/commandbox.list

install:
  # Install Commandbox
  - sudo apt-get update && sudo apt-get --assume-yes install jq commandbox ant-optional
  # Install dependencies
  - box install && box install commandbox-cfconfig,commandbox-dotenv
  # If using auto-publish, you will need to provide your API token with this line:
  - box config set endpoints.forgebox.APIToken=$FORGEBOX_API_TOKEN > /dev/null

script:
  # Execute build via ANT
  - ant -DisTravis=true -Dcfengine=$ENGINE -Dbuild.number=$TRAVIS_BUILD_NUMBER -Dbuild.branch=$TRAVIS_BRANCH -f build/build.xml
  # Set Current Version
  - BUILD_VERSION=`cat $TRAVIS_BUILD_DIR/artifacts/testbox/box.json | jq '.version' -r`
  - echo "TestBox v$BUILD_VERSION"

after_failure:
  - cd $TRAVIS_BUILD_DIR
  # Get response from test server to see what went wrong
  - curl http://localhost:49616/tests/runner.cfm?reporter=text
  # Display the contents of our root directory
  # Spit out our Commandbox log in case we need to debug
  - box server log name=$ENGINE
  - cat `box system-log`
  - ls -l $TRAVIS_BUILD_DIR/apidocs

deploy:
  # Binary Deployments
  - provider: s3
    on:
      branch:
        - master
        - development
      condition: "$ENGINE = lucee@4.5"
    skip_cleanup: true
    #AWS Credentials need to be set in Travis
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET
    bucket: "downloads.ortussolutions.com"
    local-dir: $TRAVIS_BUILD_DIR/artifacts/testbox
    upload-dir: ortussolutions/testbox
    acl: public_read

  #API Docs Deployment
  - provider: s3
    on:
      branch:
        - master
        - development
      condition: "$ENGINE = lucee@4.5"
    skip_cleanup: true
    #AWS Credentials need to be set in Travis
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET
    bucket: "apidocs.ortussolutions.com"
    local-dir: $TRAVIS_BUILD_DIR/build-testbox/testbox/apidocs
    upload-dir: testbox/$BUILD_VERSION
    acl: public_read

after_deploy:
  - cd $TRAVIS_BUILD_DIR/build-testbox/testbox
  - if [ ${ENGINE} = 'lucee@4.5' ]; then box forgebox publish; fi